# Generated by Django 3.2 on 2021-05-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('calories_in', models.IntegerField()),
                ('calories_out', models.IntegerField()),
                ('heartrate', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('protein', models.IntegerField()),
            ],
        ),
    ]
